### ISSUE TITLE
Javascript example doesn't work

### ISSUE THREAD

**Issue by Stuk** [vislyhq/stretch#30]
I was excited to try the JS API, so I tried following https://vislyhq.github.io/stretch/docs/javascript. Unfortunately it doesn't work on Node v8, v10, or v12 (the current LTS versions of Node).

On 8 and 10:

```
(function (exports, require, module, __filename, __dirname) { import { Node } from 'stretch-layout';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

On 12:

```
import { Node } from 'stretch-layout';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
```

It also doesn't look like the package is following the [modules API in the Node documentation](https://nodejs.org/api/esm.html) (`.mjs` and `type: "module"`)

**Comment by feixionglee** [comment]
I get same issue, my node is v10.13.0

**Comment by emilsjolander** [comment]
My bad, i wrote the docs to quickly without testing them all. To use web assembly you need a bundler that supports it like webpack. I've updated the documentation with working instructions. Sorry about that!

**Comment by Stuk** [comment]
Thanks for updating the docs!
