### ISSUE TITLE
Possible bug in `Stretch::remove` or `Stretch::replace_child_at_index`

### ISSUE THREAD

**Issue by yawor** [vislyhq/stretch#51]
I have a use case where I need to replace specific child nodes on an external request. These child nodes act as placeholders for dynamic content. To replace them, I'm trying to use `Stretch::replace_child_at_index`. I also need to `Stretch::remove` the old child node, which is being replaced. This combination results in a panic inside the `Stretch::replace_child_at_index` on a second replacement.

Here's a short example:
```rust
use stretch::Stretch;
use stretch::style::{Style};

fn main() {
    let mut stretch = Stretch::new();

    let child1 = stretch.new_node(Style::default(), vec![]).unwrap();
    let child2 = stretch.new_node(Style::default(), vec![]).unwrap();
    let node = stretch.new_node(Style::default(), vec![child1, child2]).unwrap();

    loop {
        println!("replacing child1");
        let new_child = stretch.new_node(Style::default(), vec![]).unwrap();
        let old_node = stretch.replace_child_at_index(node, 0, new_child).unwrap();
        stretch.remove(old_node);
        println!("done");
    }
}
```

Here's an output with a backtrace:
```
replacing child1
done
replacing child1
thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1034:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::option::expect_failed
             at src/libcore/option.rs:1034
  11: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
  12: stretch::node::Stretch::replace_child_at_index
  13: serde_tests::main
  14: std::rt::lang_start::{{closure}}
  15: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  16: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  18: std::panicking::try
             at src/libstd/panicking.rs:275
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  21: main
  22: __libc_start_main
  23: _start
```

The panic is cause by the return line in `Stretch::replace_child_at_index`:
```rust
        Ok(self.ids_to_nodes[&old_child])
```

If I remove the `stretch.remove(old_node);` line, the program doesn't panic, but it doesn't release the memory for the old nodes and the program grows very quickly in memory. This is of course a very extreme example. In my use case, the replacement would occur about every 30 seconds, so it wouldn't grow that fast, but still this is quite a big issue.

**Comment by yawor** [comment]
OK it seems I've found the error and I've created a PR with the fix. I've been running the example program and my bigger implementation and no panics anymore and the memory usage is constant.
